//! Bundled Microsoft Fluent emoji catalog. JSON is generated by
//! `just rebuild-catalog` and baked in at compile time so the daemon
//! ships standalone.

use std::collections::BTreeMap;
use std::sync::Arc;

use anyhow::{Context, Result};
use serde::Deserialize;

use crate::assets::EmojiId;

const BUNDLED_JSON: &str = include_str!("../../../../assets/fluent-catalog.json");

/// One row of the catalog. Field names mirror the JSON.
#[derive(Debug, Clone, Deserialize)]
pub(crate) struct CatalogEntry {
    pub id: String,
    pub name: String,
    pub glyph: String,
    pub group: String,
    pub keywords: Vec<String>,
    pub has_animated: bool,
    pub static_path: String,
    /// Empty when `has_animated == false`.
    pub animated_path: String,
}

#[derive(Debug)]
pub(crate) struct Catalog {
    entries: Arc<[CatalogEntry]>,
    by_id: BTreeMap<String, usize>,
}

impl Catalog {
    pub(crate) fn load_bundled() -> Result<Self> {
        let entries: Vec<CatalogEntry> =
            serde_json::from_str(BUNDLED_JSON).context("parsing bundled fluent-catalog.json")?;
        let by_id = entries
            .iter()
            .enumerate()
            .map(|(i, e)| (e.id.clone(), i))
            .collect();
        Ok(Self {
            entries: Arc::from(entries),
            by_id,
        })
    }

    pub(crate) fn entries(&self) -> &[CatalogEntry] {
        &self.entries
    }

    pub(crate) fn get(&self, id: &EmojiId) -> Option<&CatalogEntry> {
        self.by_id.get(id.as_str()).map(|&i| &self.entries[i])
    }

    pub(crate) fn len(&self) -> usize {
        self.entries.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_catalog_parses() {
        let cat = Catalog::load_bundled().expect("bundled catalog must parse");
        assert!(cat.len() > 100, "catalog suspiciously small: {}", cat.len());
        for id in ["fire", "thumbs_up", "red_heart"] {
            assert!(cat.get(&EmojiId::new(id)).is_some(), "missing id: {id}");
        }
    }
}
